CREATE DATABASE ZEPTO_SQL_PROJECT;

USE ZEPTO_SQL_PROJECT;

DROP TABLE IF EXISTS ZEPTO;

CREATE TABLE ZEPTO(
SKU_ID SERIAL PRIMARY KEY,
CATEGORY VARCHAR(120),
NAME VARCHAR(150) NOT NULL,
MRP NUMERIC(8,2),
DISCOUNTPERCENT NUMERIC(5,2),
AVAILABLEQUANTITY INTEGER,
DISCOUNTEDSELLINGPRICE NUMERIC(8,2),
WEIGHTINGMS INTEGER,
OUTOFSTOCK BOOLEAN,
QUANTITY INTEGER
);

ALTER TABLE ZEPTO
MODIFY OUTOFSTOCK VARCHAR(10);



-- DATA EXPLORATION

SELECT COUNT(*)
FROM ZEPTO;


-- SAMPLE DATA
SELECT *
FROM ZEPTO
LIMIT 10;


-- DIFFERENT CATEGORIES
SELECT DISTINCT CATEGORY
FROM ZEPTO
ORDER BY CATEGORY;


-- ITEMS OUT OF STOCK
SELECT OUTOFSTOCK, COUNT(*)
FROM ZEPTO
GROUP BY OUTOFSTOCK;


-- PRODUCT NAMES PRESENT MULTIPLE TIMES
SELECT NAME
FROM ZEPTO
GROUP BY NAME
HAVING COUNT(NAME) > 1
ORDER BY NAME;



-- DATA CLEANING

-- PRODUCTS WITH PRICE = 0
SELECT *
FROM ZEPTO
WHERE MRP = 0 OR DISCOUNTEDSELLINGPRICE = 0;


DELETE FROM ZEPTO
WHERE MRP = 0;


-- UPDATE PAISE TO RUPEES
UPDATE ZEPTO
SET DISCOUNTEDSELLINGPRICE = DISCOUNTEDSELLINGPRICE / 100;

UPDATE ZEPTO
SET MRP = MRP / 100;


SELECT *
FROM ZEPTO
LIMIT 10;



-- Q1. FIND THE TOP 10 BEST-VALUE PRODUCTS BASED ON THE DISCOUNT PERCENTAGE.

SELECT NAME, MRP, DISCOUNTPERCENT
FROM ZEPTO
ORDER BY DISCOUNTPERCENT DESC
LIMIT 10;



-- Q2. WHAT ARE THE PRODUCTS WITH HIGH MRP BUT CURRENTLY OUT OF STOCK?

SELECT DISTINCT NAME, MRP
FROM ZEPTO
WHERE OUTOFSTOCK = 'TRUE'
AND MRP > 300
ORDER BY MRP DESC;



-- Q3. CALCULATE THE ESTIMATED REVENUE FOR EACH CATEGORY.

SELECT CATEGORY,
SUM(DISCOUNTEDSELLINGPRICE * AVAILABLEQUANTITY) AS TOTAL_REVENUE
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY TOTAL_REVENUE;



-- Q4. FIND ALL PRODUCTS WHERE MRP IS GREATER THAN ₹500 AND THE DISCOUNT IS LESS THAN 10%.

SELECT DISTINCT NAME, MRP, DISCOUNTPERCENT
FROM ZEPTO
WHERE MRP > 500
AND DISCOUNTPERCENT < 10
ORDER BY MRP DESC, DISCOUNTPERCENT DESC;



-- Q5. IDENTIFY THE TOP 5 CATEGORIES OFFERING THE HIGHEST AVERAGE DISCOUNT PERCENTAGE.

SELECT CATEGORY,
ROUND(AVG(DISCOUNTPERCENT),2) AS AVG_DISCOUNT
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY AVG_DISCOUNT DESC
LIMIT 5;



-- Q6. FIND THE PRICE PER GRAM FOR PRODUCTS ABOVE 100G AND SORT THEM BY BEST VALUE.

SELECT DISTINCT NAME, MRP, DISCOUNTEDSELLINGPRICE,
ROUND(DISCOUNTEDSELLINGPRICE / WEIGHTINGMS,2) AS PRICE_PER_GRAM
FROM ZEPTO
WHERE WEIGHTINGMS >= 100
ORDER BY PRICE_PER_GRAM DESC;



-- Q7. GROUP THE PRODUCTS INTO CATEGORIES LIKE LOW, MEDIUM, AND BULK BASED ON WEIGHT.

SELECT DISTINCT NAME, WEIGHTINGMS,
CASE
WHEN WEIGHTINGMS < 1000 THEN 'LOW'
WHEN WEIGHTINGMS < 5000 THEN 'MEDIUM'
ELSE 'BULK'
END AS WEIGHT_CATEGORY
FROM ZEPTO;



-- Q8 WHAT IS THE TOTAL INVENTORY WEIGHT PER CATEGORY

SELECT CATEGORY,
SUM(WEIGHTINGMS * AVAILABLEQUANTITY) AS TOTAL_WEIGHT
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY TOTAL_WEIGHT;



-- Q9 WHICH CATEGORIES GENERATED HIGHEST REVENUE

SELECT CATEGORY,
SUM(DISCOUNTEDSELLINGPRICE * AVAILABLEQUANTITY) AS REVENUE
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY REVENUE DESC;



-- Q10 WHICH CATEGORIES HAVE THE HIGHEST AVERAGE DISCOUNT?

SELECT CATEGORY,
ROUND(AVG(DISCOUNTPERCENT),2) AS AVG_DISCOUNT
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY AVG_DISCOUNT DESC;



-- Q11 WHICH PRODUCTS PROVIDE THE BEST VALUE PER GRAM?

SELECT NAME,
DISCOUNTEDSELLINGPRICE,
WEIGHTINGMS,
(DISCOUNTEDSELLINGPRICE / WEIGHTINGMS) AS PRICE_PER_GRAM
FROM ZEPTO
WHERE WEIGHTINGMS > 0
ORDER BY PRICE_PER_GRAM ASC
LIMIT 10;



-- Q12 WHICH CATEGORIES HAVE THE HIGHEST STOCK LEVELS?

SELECT CATEGORY,
SUM(AVAILABLEQUANTITY) AS TOTAL_STOCK
FROM ZEPTO
GROUP BY CATEGORY
ORDER BY TOTAL_STOCK DESC;